name: Build and Push Docker Image

on:
  push:
    branches: [main]
env:
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}

      - name: deploy-dev
        uses: th0th/rancher-redeploy-workload@v0.9
        env:
          RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
          RANCHER_URL: 'https://rancher.mun.sh'
          RANCHER_CLUSTER_ID: 'local'
          RANCHER_PROJECT_ID: 'p-vdwsg'
          RANCHER_NAMESPACE: 'default'
          RANCHER_WORKLOADS: 'rgb'

      - name: deploy-dev
        uses: th0th/rancher-redeploy-workload@v0.9
        env:
          RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
          RANCHER_URL: 'https://rancher.mun.sh'
          RANCHER_CLUSTER_ID: 'local'
          RANCHER_PROJECT_ID: 'p-vdwsg'
          RANCHER_NAMESPACE: 'default'
          RANCHER_WORKLOADS: 'rgb-browser'